### ISSUE TITLE
Operational Pattern Identification Universal Label 

### ISSUE THREAD

**Issue by jpviollet** [SMPTE/st429-20#24]
About the Operational Pattern Identification Universal Label:

. ST 377:2004, Table 6, specifies its Byte 8th as "01h" (hardcoded in ST 377:2004)
. ST 377-1:2019 Table 9 specifies this same byte as “vvh”, meaning that we must go read the SMPTE Register to get actual value if I am not wrong - and in the SMPTE Labels Register, the value used for OP Atoms (as used in D-Cinema) seems “02h”.
. ST 390:2011 (OP Atom spec) refers to "the MXF File Format Specification" (NOT to the SMPTE Register) to know the bytes 1-12 of this Label - and as such, for ST377:2004-based implementations, a value of 01h would remain expected.

I don't expect this to create an actual issue, as I think typically implementations ignore such version Byte 8th, however maybe some don't (to be confirmed - I am currently checking for our implementations), and it remains a difference anyway that may trigger question for people noticing it and wondering which value they should use - and at the very minimum, a guidance about this in our constraints document seems appropriate. Hope it makes sense. Thank you in advance.

Labels impacted seem to be:

urn:smpte:ul:060e2b34.04010102.0d010201.10000000   MXF-OP Atom 1 Track 1 SourceClip
urn:smpte:ul:060e2b34.04010102.0d010201.10010000   MXF-OP Atom 1 Track N SourceClip
urn:smpte:ul:060e2b34.04010102.0d010201.10020000   MXF-OP Atom N Track 1 SourceClip
urn:smpte:ul:060e2b34.04010102.0d010201.10030000   MXF-OP Atom N Track N SourceClip

**Comment by jpviollet** [comment]
I would personally not repeat this note, and certainly not as-is, as I don't think it really helps avoid an issue - and we expect the reader of ST 429-20 to rely on ST377-1:2019 already, which I think was why you asked your question.

In fact, this note does NOT say "shall ignore" and not even "should ignore", it says "can ignore" - as I believe it cannot exactly repeat the "may ignore" actually written in ST 336 (due to normative language vs Informative Note if I am not wrong). This means that implementers can very well still make the decision to actually reject a file that does not have proper version number - and some existing 2004-based implementation could be doing this already maybe.

As our goal here is to specify how to create a file that matches ST377:2004 based files, it feels we don't really have the choice and we have to indicate that 01h has to be used instead of 02h for ST377:2004 compliance. However, when doing this, maybe it would be a good opportunity to add a stronger statement that would apply to D-Cinema application only (trying to mitigate the issue of 01h vs 02h), maybe something like: 

"KLV parsers should ignore the version number"

Would this make sense?

**Comment by palemieux** [comment]
> "KLV parsers should ignore the version number"

+1

**Comment by palemieux** [comment]
@jpviollet See https://smpte.sharepoint.com/:w:/s/21DC-DocumentMaintenance/Eal2gNBYVRNBjnoj0QMW2CIB8KCzUtG2OmEgkWcltezUOw?e=oYFZ01

**Comment by jpviollet** [comment]
Thank you for this update. However, it does NOT resolve my comment because it only targets "UL Key of a KLV Triplet". And my comment was specifically related to the "Operational Pattern Identification Universal Label" which it is NOT a UL Key of a KLV triplet (it is a Label indicating which Operational Pattern is used by the MXF file.)

Also, I think we do need to explicitly point out this "Operational Pattern Identification Universal Label" byte 8th difference in our constraints document to mitigate as much as possible any issue it could trigger if not known by implementers. And to obtain a strictly 2004-compliant file (objective of our document), we may have to indicate that a Byte 8th value of "01h" should be used - in case any existing implementation would reject any other value. Hope it makes sense. Thank you.

**Comment by palemieux** [comment]
Per 2022-02-10 meeting:

* ASDCPLib writes `0x02` as the version number of the OP Atom UL
* in addition to recommending ignoring the version number of the OP UL, the version number of UL Keys should also be ignored.

**Comment by palemieux** [comment]
Addressed at https://smpte.sharepoint.com/:w:/s/21DC-DocumentMaintenance/Eb6LVvw_zR9AiSAPtka9OTsBbAk8GCHqVg1fuq1kg8YF9Q?e=kho09I

**Comment by jpviollet** [comment]
The proposed added section 6 does NOT resolve my comment, sorry.

I received feedback from our R&D, and Operational Pattern identification UL Byte 8th value is used in our equipment to differentiate SMPTE content from Interop content, and Byte 8th set to 0x02 means SMPTE. A different processing is then applied if content is SMPTE compared to Interop – meaning that our equipment expects 0x02 to properly reproduce SMPTE DCP.

A Byte 8th of 0x01 is clearly specified in Interop spec, with a Note explaining that the officially registered SMPTE Byte 8th is 0x02 – making 0x02 the clear specified SMPTE value, despite what is written in ST377:2004 that people may have considered a typo compared to the official SMPTE Register value. As illustrated by ASDCPLib and our implementations, it looks like the value 0x02 is globally used for SMPTE DCP – any other value would have triggered an issue that would have been reported to us, and we did not hear about this.

Also, the Byte 8th ST336 provision is written in a way that seems to only target a “Key” of a KLV triplet (NOT a “Label” like this Operational Pattern UL) and the similar statement in ST377-1:2019 is located in section “6.3 KLV Coding” which addresses Sets and Packs KLV coding – NOT a “Label”, which is only a data used in a Value field of a KLV triplet. This makes this Byte 8th NOT expected to be ignored so far.

Based on the above, the following changes would resolve my comment:

. Replace “_The version number (byte 8) of the Operational Pattern identification UL should be ignored_” with “**_The version number (byte 8) of the Operational Pattern identification UL should be set to 0x02_**”.

. Add a Note 3, stating: “**_Note 3: Some implementations do NOT ignore Byte 8th of the OP Atom Operational Pattern identification UL and expect its value to be 0x02 in MXF files used in SMPTE DCP - another value can trigger unexpected behaviors. MXF files used in non-SMPTE DCP are out of scope if this document and can use a different Byte 8th value as defined in their respective specifications._**”

. **Delete section 6.2** – in fact, after further thinking, I don’t see a reason to add this “should” statement as no issue has been detected that requires the need to make existing ST336/ST377-1:2019 KLV Key Byte 8th provisions stronger (here it is a Label, not a Key), and as such, in the spirit of “don’t fix what is not broken”, it feels safer to remove section 6.2 to avoid possibly introducing issues/confusion (especially as ST336/ST377-1:2019 do say that this Byte 8th can be used as an additional guide and consistency check in the process of parsing a KLV Key.)

Thank you in advance.

**Comment by palemieux** [comment]
@jpviollet See revised draft at https://smpte.sharepoint.com/:w:/s/21DC-DocumentMaintenance/EWOQce9c175Gqvj4HMxeC1wBS_whHu6XMwwt19Ch_zAerg?e=Gy9Zl1

**Comment by jpviollet** [comment]
The revised draft resolved my comment, thank you.
